config/routes.rb
Rails.application.routes.draw do
  # resources :messages

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }    
  root to: "home#index"
  resources :posts do
    put '/like', to: 'likes#like'
    put '/dislike', to: 'likes#dislike'
  end

  resources :comments

  resources :friend_requests, only: [:create] do 
    collection do
      post :accept
      post :reject
    end
  end 

  resources :rooms
  resources :users  
  # root 'rooms#index'
  resources :rooms do
    resources :messages
  end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
    def index
      @post = Post.new
      @posts = Post.all.order(created_at: :desc)
      # @posts = current_user.posts.includes(:comments).order(created_at: :desc)
      @comment = Comment.new
      # binding.pry
      # @comments = Comment.all.order(created_at: :desc)
      # @like = Like.new
      # @likes = Like.all
      # render
    end

end

app/views/home/_addfriend.html.erb
 <h5 class="pt-5">ADD Friend</h5>
        <div class="request1 scroll1"> 
              <% not_friend.each do |i|%>
                <%user = get_user(i)%>
                  <div class="d-flex justify-content-between request">
                      <span><%=image_tag user.image ,class:"image1 mx-2" rescue image_tag 'default.jpg', class: "mx-2 image1" %>
                      <%=user.firstname%>  <%= user.lastname%></span>
                  
                        <%unless check_friend_request_sent(current_user.id , user.id)%>
                          <span><%= button_to "add friend", friend_requests_path(:receive_id => user.id), class: "btn btn-primary" %></span> 
                        <%else%>
                          <span><%= button_to "Pending",{},:disabled => true, class: "btn btn-secondary" %></span>
                        <%end%>
                  </div>    
              <%end%>
        </div>

app/views/home/_footer.html.erb
<div>
  <footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-linkedin"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">W3Villa.com</a>
  </div>
  <!-- Copyright -->
</footer>
</div>

app/views/home/_friendslist.html.erb
 <span class="pt-5 d-flex"><h5 >FRIENDS LIST</h5>
<h5 class="pl-2">(<%=friendships.count%>)</h5>
</span>
    <div class="pad2 request scroll"> 
        <%friendships.each do |user|%>
            <div class="">
                <span><%= image_tag user.image ,class:"image1 mx-2" rescue image_tag 'default.jpg', class: "mx-2 image1" %></span>
                <span><%= get_user(user.user_id).username %></span>
            </div>
            <hr>
        <%end%>
    </div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <%# <a class="navbar-brand" href="#">Navbar</a> %>
  <i class="fa fa-vk" aria-hidden="true"></i>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">W3V-Social <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 padding1">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <span class="px-3"><%=image_tag current_user.image.variant(resize: "50x50"), class:"image1" rescue image_tag 'default.jpg', class:"image1"%></span>
    </form>
  </div>
</nav>

app/views/home/_post.html.erb
        <div class= "border3 p-3">
            <%= form_with model: @post, class: "d-flex align-items-center" do |f| %>
              <%= image_tag current_user.image.variant(resize: "50x50"), class:"image1" rescue image_tag 'default.jpg', class:"image1"%>
              <%= f.text_field :title, placeholder:"What's new #{current_user.username}", class:"removeborder px-3"%>
              <span class='select-wrapper'>
                <i class="fa fa-camera" aria-hidden="true"></i>
                <%= f.file_field :images, id: 'image_src', label: "Photos" %>
              </span>
              <%= f.submit "Create Post" , class: "btn btn-primary"%>
            <% end %>
        </div>

        <div class="post">
          <% @posts.each do |post| %>
            <div class="border5 padding5">
              <div class="post d-flex">
                <span><%=image_tag post.user.image.variant(resize: "50x50"),class:"image1"  rescue image_tag 'default.jpg', class:"image1"%></span>
                <div class="px-3 ">
                  <span class="titlebold"><%= post.user.username %></span>
                  </br>
                  <%="#{calculate_time(post.created_at)}"%>
                  </#br>
                </div>  
              </div>  
              <div class="post titlebold">
                <span><%=post.title%></span>
              </div>
              <% unless post.images.count == 0 %>
                <div class="post-loop">
                  <%=image_tag post.images.first%>
                </div>
              <%end%>
              <div class='post d-flex' id="like<%=post.id%>">
                <% unless post.is_liked?(current_user) %>
                  <%#= link_to post_like_path(post_id: post),method: "put"  do %>
                    <i class="fa fa-thumbs-o-up likesize like-unlike" aria-hidden="true" id="<%= post.id %>" ></i>
                  <%# end %>
                <% else %>
                  <%#= link_to post_dislike_path(post_id: post), method: "put" do %>
                    <i class="fa fa-thumbs-up likesize like-unlike" aria-hidden="true" id="<%= post.id %>" ></i>
                  <%# end %>
                <% end %>
                <div class='px-2'>
                    <%= post.likes.sum(:count) %>
                </div>
              </div>
              <hr>
              <div class=" like border3 pb-3">
                  <%= form_with model: @comment, class: "d-flex" do |f| %>
                    <%= f.text_field :message, placeholder:"Write a comment", class:"removeborder"%>
                    <%#= f.file_field :images, multiple: true, placeholder: "image"%>
                    <%= f.hidden_field :post_id, value: post.id %>
                    <%= f.submit "Comment" , class: "btn btn-primary"%>
                  <% end %>
              </div>
            
            </div>

              <div class="post padding4">
                <tbody>
                  <% comment_order(post.comments).each do |comment| %>
                    <tr class="tr-success post">
                        <div class="colorcomment pad1">
                          <% if comment.user.present?%>
                            <div class="post titlebold"> 
                              <span><%=image_tag comment.user.image.variant(resize: "30x30"), class:"image1" rescue image_tag 'default.jpg', class:"image1"%></span>
                              <span><%=comment.user.username %> 
                              [<%= comment.created_at.strftime("%I:%M %p")%>]
                            </div>
                            <div class="">
                              <span><%= comment.message%></span>
                            </div>
                          <%end%>
                        </div> 
                    </tr>
                  <%end%> 
                </tbody>
                  <%##this is the end of Post model 148 line%>
              </div>
          <%end%>
        </div> 



<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>

$('.like-unlike').on('click', function(){
    var id = this.id;
    if ($(this).hasClass('fa-thumbs-o-up')) {
  debugger
      $.ajax({
            type: 'PUT',
            url: 'posts/'+ id +'/like'
      });
      $(this).removeClass('fa-thumbs-o-up').addClass('fa-thumbs-up');
      var like = +this.nextElementSibling.innerText + 1;
      this.nextElementSibling.innerText = like;
    }
    // else {
    // debugger
    //   $.ajax({
    //     type: 'PUT',
    //     url: 'posts/'+ id +'/like'
    //   })
    //   $(this).removeClass('fa-thumbs-up').addClass('fa-thumb-o-down');
    //   var dislike = +this.nextElementSibling.innerText + 1;
    //   this.nextElementSibling.innerText = like;

    // }
})

$('.')

</script>

app/views/home/_request.html.erb
<span class="d-flex"><h5>REQUESTS</h5>
        <h5 class="pl-2">(<%= check_incoming_friend_request.count%>)</h5>
</span>
    <div>
        <% check_incoming_friend_request.each do |user|%>  
            <div class="request"> 
            <div class="d-flex">
                <div class="pb-1"><%=image_tag user.requester.image.variant(resize: "30x30"),class:"image1" rescue image_tag 'default.jpg', class: "image1" %></div>
                <div class="pb-3 px-3"><%=get_user(user.requester_id).firstname %> wants to add you to friends</div>
            </div>
            <div class="px-5">
                <td><%= link_to "Accept", accept_friend_requests_path(:receive_id => user.requester_id),method: :post, class: "btn btn-primary d-inline-block" %></td>
                <td><%= link_to "Decline", reject_friend_requests_path(:receive_id => user.requester_id), method: :post, class: "btn btn-danger d-inline-block" %></td>
            </div>
            </div>
        <%end%>
    </div>

app/views/home/_sidenav.html.erb
<div class="sticky">
    <div class="padding4">
        <div>
            <%=image_tag current_user.image.variant(resize: "50x50"),class:"image" rescue image_tag 'default.jpg', class:"image1 mr-3"%>
            <span class="pl-3"><%=current_user.username%></span> 
        </div>
    </div>
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-light sidenav ">
        <ul class="nav nav-pills flex-column mb-auto boader">
            <% tab_options.each do |tab| %>
                <li class="nav-item boader">
                <a href="<%= sidebarUrl(tab[0]) %>" class="nav-link link-dark " aria-current="page">
                    <i class="pr-4 fa fa-<%=tab[1]%>" aria-hidden="true"></i>
                    <span class="bi me-2" width="16" height="16"></span>
                        <%= tab[0] %>
                </a>
                </li>
            <%end%>
                <li class="nav-item boader">
                <a href="#" class="nav-link link-dark pr-0">
                    <i class="fa fa-cog" aria-hidden="true"></i>
                    <% if user_signed_in? %>
                    <%= link_to "Sign_out", destroy_user_session_path(), method: :delete, data: {confirm: "are you sure you want to logout"}, class: "nav-link" %>
                    <% else %>
                    <%= link_to "Sign_in", new_user_session_path, class: "nav-link bg-primary"  %> 
                    <% end %>
                </a>
                </li>
        </ul>
    </div>
</div>    

app/views/home/index.html.erb
<a id="button"></a>
<div class="content body1">
    <%= render partial: 'navbar'%>
        <div class="container-fluid">
          <div class="row top1 ">
              <div class="col-2">
                  <%= render partial: 'sidenav'%>
              </div>

              <div class="col-5">
                <%= render partial: 'post'%>
              </div>
              <div class='post d-flex' id= "divreload">
              </div>
              <div class="col-3">
                <div class="sticky">
                  <%= render partial: 'request'%>
                
                  <%= render partial: 'friendslist'%>

                  <%= render partial: 'addfriend'%>
                </div>              
              </div>
          </div>

</div>
  <%= render partial: 'footer'%>




<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript">


var btn = $('#button');

$(window).scroll(function() {
  if ($(window).scrollTop() > 300) {
    btn.addClass('show');
  } else {
    btn.removeClass('show');
  }
});

btn.on('click', function(e) {
  e.preventDefault();
  document.documentElement.scrollTop = 0;
  return false;
});
</script>